[target.'avr-atmega16a']
rustflags = [
  "-C", "target-cpu=atmega16",
  "-C", "link-arg=-Wl,--gc-sections",
]
runner = "avrdude -c usbasp -p m16 -U flash:w:${CARGO_TARGET_DIR}/avr-atmega16a/release/atmega16a-firmware.hex:e"

[alias]
build-fw = "build --features firmware --release --target targets/avr-atmega16a.json -Zbuild-std=core,compiler_builtins"
test-host = "test --target x86_64-pc-windows-msvc --no-default-features"